// <auto-generated />
using CRUDAPIs.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDAPIs.Infrastructure.Migrations
{
    [DbContext(typeof(MySQLDBContext))]
    partial class MySQLDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CRUDAPIs.Domain.Domain.DataBase.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "POR ASIGNAR"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "CLIENTE"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "COM. EXT"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "COMERCIALIZADORA"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "COTIZACIONES PARA COMERCIAL"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "DHL"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Ei CARGA"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "IOM DE MEXICO"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "MSL"
                        });
                });

            modelBuilder.Entity("CRUDAPIs.Domain.Domain.DataBase.Comentarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Comentarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "SIN COMENTARIOS"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "APOYO A OTRA ÁREA"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "BÚSQUEDA DE INFORMACIÓN PARA CLASIFICAR"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "CATÁLOGO DE PRODUCTOS"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "DINÁMICAS"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "FALLA DEL SISTEMA"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "FALTA DE INFORMACIÓN DEL CLIENTE"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "MANTENIMIENTO EQUIPO"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "MISCELÁNEA"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "REUNIÓN"
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "VACACIONES / INCAPACIDAD / VACANTE"
                        });
                });

            modelBuilder.Entity("CRUDAPIs.Domain.Domain.DataBase.Consultas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtendidoPorId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("ComentariosId")
                        .HasColumnType("int");

                    b.Property<string>("CorreoCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DiasRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("FechaCierre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FechaLlegada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoraCierre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoraLlegada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Partidas")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TituloCorreo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AtendidoPorId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ComentariosId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("CRUDAPIs.Domain.Domain.DataBase.Ejecutivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdEmpleado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ejecutivos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdEmpleado = "000000",
                            Nombre = "POR ASIGNAR"
                        },
                        new
                        {
                            Id = 2,
                            IdEmpleado = "000000",
                            Nombre = "ALEJANDRA"
                        },
                        new
                        {
                            Id = 3,
                            IdEmpleado = "000000",
                            Nombre = "ROSARIO"
                        });
                });

            modelBuilder.Entity("CRUDAPIs.Domain.Domain.DataBase.Consultas", b =>
                {
                    b.HasOne("CRUDAPIs.Domain.Domain.DataBase.Ejecutivo", "AtendidoPor")
                        .WithMany()
                        .HasForeignKey("AtendidoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDAPIs.Domain.Domain.DataBase.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDAPIs.Domain.Domain.DataBase.Comentarios", "Comentarios")
                        .WithMany()
                        .HasForeignKey("ComentariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtendidoPor");

                    b.Navigation("Cliente");

                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
